BUDDHIST_TIBETAN_SYMBOLS = {
    "dharma_wheel": {
        "name": "چرخ دارما",
        "culture": "بودایی",
        "energy": ["آگاهی", "تعادل"],
        "uses": ["spiritual", "calm"],
        "description": "نماد مسیر آگاهی و تعادل در بودیسم.",
    },
    "endless_knot": {
        "name": "گرهٔ بی‌پایان",
        "culture": "تبتی",
        "energy": ["پیوستگی", "هماهنگی"],
        "uses": ["general", "calm"],
        "description": "نماد پیوستگی انرژی و هماهنگی کیهانی.",
    },
    "lotus_buddhist": {
        "name": "لوتوس بودایی",
        "culture": "بودایی",
        "energy": ["پاکی", "رشد معنوی"],
        "uses": ["spiritual", "calm"],
        "description": "نماد پاکی، بیداری و رشد معنوی.",
    },
    "vajra": {
        "name": "واجرا",
        "culture": "تبتی",
        "energy": ["قدرت معنوی", "ثبات"],
        "uses": ["spiritual", "protection"],
        "description": "نماد قدرت معنوی و استحکام در بودیسم تبتی.",
    },
    "ghanta_bell": {
        "name": "ناقوس گانتا",
        "culture": "تبتی",
        "energy": ["آگاهی", "پاکی"],
        "uses": ["spiritual", "calm"],
        "description": "ناقوس آیینی؛ نماد آگاهی و پاکی ذهن.",
    },
    "mani_stone": {
        "name": "سنگ مانی",
        "culture": "تبتی",
        "energy": ["رحمت", "آرامش"],
        "uses": ["calm", "spiritual"],
        "description": "سنگ‌های مقدس با مانتراهای بودایی؛ نماد رحمت و آرامش.",
    },
    "om_mani_padme_hum": {
        "name": "اوم مانی پدمه هوم",
        "culture": "تبتی",
        "energy": ["رحمت", "آگاهی"],
        "uses": ["spiritual", "calm"],
        "description": "مانترای مشهور تبتی؛ نماد رحمت و آگاهی.",
    },
    "stupa": {
        "name": "استوپا",
        "culture": "بودایی",
        "energy": ["آگاهی", "تعالی"],
        "uses": ["spiritual"],
        "description": "ساختار مقدس بودایی؛ نماد آگاهی و تعالی.",
    },
    "dorje": {
        "name": "دورجه",
        "culture": "تبتی",
        "energy": ["قدرت", "محافظت"],
        "uses": ["protection", "spiritual"],
        "description": "نماد قدرت معنوی و محافظت.",
    },
    "tibetan_mandala": {
        "name": "ماندالای تبتی",
        "culture": "تبتی",
        "energy": ["تعادل", "تمرکز"],
        "uses": ["calm", "spiritual"],
        "description": "نقش هندسی مقدس برای تمرکز و تعادل.",
    },
    "eight_auspicious_symbols": {
        "name": "هشت نماد فرخنده",
        "culture": "بودایی",
        "energy": ["برکت", "آگاهی"],
        "uses": ["general", "spiritual"],
        "description": "مجموعهٔ هشت نماد مقدس بودایی برای برکت و آگاهی.",
    },
    "tibetan_prayer_flag": {
        "name": "پرچم دعا تبتی",
        "culture": "تبتی",
        "energy": ["برکت", "آرامش"],
        "uses": ["general", "calm"],
        "description": "پرچم‌های رنگی دعا؛ نماد برکت و آرامش.",
    },
    "tibetan_prayer_wheel": {
        "name": "چرخ دعا",
        "culture": "تبتی",
        "energy": ["آگاهی", "رحمت"],
        "uses": ["spiritual"],
        "description": "چرخ دعا برای گسترش انرژی مثبت و آگاهی.",
    },
    "bodhi_leaf": {
        "name": "برگ بودی",
        "culture": "بودایی",
        "energy": ["آگاهی", "بیداری"],
        "uses": ["spiritual", "calm"],
        "description": "برگ درخت بودی؛ نماد بیداری و آگاهی.",
    },
    "tibetan_snow_lion": {
        "name": "شیر برفی تبتی",
        "culture": "تبتی",
        "energy": ["قدرت", "شجاعت"],
        "uses": ["success", "protection"],
        "description": "نماد قدرت، شجاعت و انرژی مثبت.",
    },
    "vajra_bell_set": {
        "name": "ست واجرا و ناقوس",
        "culture": "تبتی",
        "energy": ["تعادل", "آگاهی"],
        "uses": ["spiritual"],
        "description": "ترکیب واجرا و ناقوس؛ نماد تعادل نیروهای معنوی.",
    },
    "tibetan_cloud": {
        "name": "ابر تبتی",
        "culture": "تبتی",
        "energy": ["جریان", "آرامش"],
        "uses": ["calm", "general"],
        "description": "نماد جریان انرژی و آرامش.",
    },
    "tibetan_dragon": {
        "name": "اژدهای تبتی",
        "culture": "تبتی",
        "energy": ["قدرت", "محافظت"],
        "uses": ["protection", "success"],
        "description": "نماد قدرت و محافظت معنوی.",
    },
    "tibetan_flower": {
        "name": "گل تبتی",
        "culture": "تبتی",
        "energy": ["زیبایی", "تعادل"],
        "uses": ["general", "calm"],
        "description": "نماد زیبایی، تعادل و هماهنگی.",
    },
    "tibetan_sun_moon": {
        "name": "خورشید–ماه تبتی",
        "culture": "تبتی",
        "energy": ["تعادل", "آگاهی"],
        "uses": ["spiritual", "calm"],
        "description": "ترکیب خورشید و ماه؛ نماد تعادل و آگاهی.",
    },
}
