CELTIC_SYMBOLS = {
    "triskelion": {
        "name": "تریسکل (Triskelion)",
        "culture": "سلتی",
        "energy": ["حرکت", "رشد", "قدرت"],
        "uses": ["success", "spiritual"],
        "description": "نماد سه‌گانهٔ حرکت و رشد؛ یکی از مهم‌ترین نمادهای سلتی.",
    },
    "triquetra": {
        "name": "تریکوترا",
        "culture": "سلتی",
        "energy": ["تعادل", "هماهنگی"],
        "uses": ["calm", "general"],
        "description": "نماد سه‌گانهٔ تعادل میان ذهن، جسم و روح.",
    },
    "celtic_knot": {
        "name": "گرهٔ سلتی",
        "culture": "سلتی",
        "energy": ["پیوستگی", "حفاظت"],
        "uses": ["protection", "general"],
        "description": "گره‌های بی‌پایان سلتی؛ نماد پیوستگی و محافظت.",
    },
    "claddagh": {
        "name": "کلادا",
        "culture": "سلتی/ایرلندی",
        "energy": ["عشق", "وفاداری"],
        "uses": ["love"],
        "description": "نماد عشق، وفاداری و دوستی.",
    },
    "celtic_tree_of_life": {
        "name": "درخت زندگی سلتی",
        "culture": "سلتی",
        "energy": ["رشد", "حکمت"],
        "uses": ["spiritual", "general"],
        "description": "نماد اتصال میان زمین و آسمان؛ رشد و حکمت.",
    },
    "awen": {
        "name": "آوِن",
        "culture": "درویدی/سلتی",
        "energy": ["الهام", "خلاقیت"],
        "uses": ["success", "spiritual"],
        "description": "نماد الهام شاعرانه و انرژی خلاق.",
    },
    "celtic_cross": {
        "name": "صلیب سلتی",
        "culture": "سلتی",
        "energy": ["تعادل", "نور"],
        "uses": ["spiritual", "general"],
        "description": "ترکیب صلیب و دایره؛ نماد تعادل و نور.",
    },
    "spiral": {
        "name": "مارپیچ سلتی",
        "culture": "سلتی",
        "energy": ["رشد", "چرخهٔ زندگی"],
        "uses": ["spiritual", "calm"],
        "description": "نماد چرخهٔ زندگی و رشد معنوی.",
    },
    "double_spiral": {
        "name": "مارپیچ دوگانه",
        "culture": "سلتی",
        "energy": ["تعادل", "تغییر"],
        "uses": ["calm", "general"],
        "description": "نماد تعادل میان نیروهای متضاد.",
    },
    "celtic_stag": {
        "name": "گوزن سلتی",
        "culture": "سلتی",
        "energy": ["قدرت", "شجاعت"],
        "uses": ["success", "protection"],
        "description": "نماد قدرت، شجاعت و طبیعت.",
    },
    "celtic_boar": {
        "name": "گراز سلتی",
        "culture": "سلتی",
        "energy": ["قدرت", "اراده"],
        "uses": ["success"],
        "description": "نماد ارادهٔ قوی و شجاعت.",
    },
    "celtic_dragon": {
        "name": "اژدهای سلتی",
        "culture": "سلتی",
        "energy": ["قدرت", "حفاظت"],
        "uses": ["protection", "success"],
        "description": "نماد قدرت و محافظت در اسطوره‌های سلتی.",
    },
    "celtic_horse": {
        "name": "اسب سلتی",
        "culture": "سلتی",
        "energy": ["آزادی", "قدرت"],
        "uses": ["success", "general"],
        "description": "نماد آزادی، قدرت و حرکت.",
    },
    "celtic_wolf": {
        "name": "گرگ سلتی",
        "culture": "سلتی",
        "energy": ["حکمت", "محافظت"],
        "uses": ["protection", "spiritual"],
        "description": "نماد خرد و محافظت.",
    },
    "celtic_sun": {
        "name": "خورشید سلتی",
        "culture": "سلتی",
        "energy": ["نور", "قدرت"],
        "uses": ["success", "general"],
        "description": "نماد خورشید و انرژی مثبت.",
    },
    "celtic_moon": {
        "name": "ماه سلتی",
        "culture": "سلتی",
        "energy": ["آرامش", "شهود"],
        "uses": ["calm", "spiritual"],
        "description": "نماد ماه و انرژی شهودی.",
    },
    "celtic_shield": {
        "name": "سپر سلتی",
        "culture": "سلتی",
        "energy": ["محافظت", "قدرت"],
        "uses": ["protection"],
        "description": "نماد محافظت و قدرت جنگجویان سلتی.",
    },
    "celtic_knot_circle": {
        "name": "گرهٔ دایره‌ای سلتی",
        "culture": "سلتی",
        "energy": ["پیوستگی", "تعادل"],
        "uses": ["general", "calm"],
        "description": "ترکیب دایره و گره؛ نماد پیوستگی و تعادل.",
    },
    "celtic_raven": {
        "name": "کلاغ سلتی",
        "culture": "سلتی",
        "energy": ["حکمت", "بینش"],
        "uses": ["spiritual"],
        "description": "نماد بینش و خرد پنهان.",
    },
    "celtic_triple_goddess": {
        "name": "الههٔ سه‌گانهٔ سلتی",
        "culture": "سلتی",
        "energy": ["چرخهٔ زندگی", "تعادل"],
        "uses": ["spiritual", "general"],
        "description": "نماد سه مرحلهٔ زندگی: دختر، مادر، پیرزن.",
    },
}
