EGYPTIAN_SYMBOLS = {
    "ankh": {
        "name": "عنخ",
        "culture": "مصر باستان",
        "energy": ["زندگی", "قدرت", "تعادل"],
        "uses": ["spiritual", "general"],
        "description": "نماد زندگی جاودانه و تعادل در مصر باستان.",
    },
    "eye_of_horus": {
        "name": "چشم هوروس",
        "culture": "مصر باستان",
        "energy": ["محافظت", "سلامت"],
        "uses": ["protection", "general"],
        "description": "نماد محافظت، سلامت و بینش.",
    },
    "eye_of_ra": {
        "name": "چشم رع",
        "culture": "مصر باستان",
        "energy": ["قدرت", "نور"],
        "uses": ["success", "protection"],
        "description": "نماد قدرت خورشیدی و محافظت الهی.",
    },
    "scarab": {
        "name": "سوسک مقدس",
        "culture": "مصر باستان",
        "energy": ["تولد دوباره", "موفقیت"],
        "uses": ["success", "spiritual"],
        "description": "نماد تولد دوباره، حرکت و موفقیت.",
    },
    "lotus_egypt": {
        "name": "لوتوس مصری",
        "culture": "مصر باستان",
        "energy": ["پاکی", "آگاهی"],
        "uses": ["spiritual", "calm"],
        "description": "نماد پاکی، بیداری و آگاهی.",
    },
    "djed": {
        "name": "ستون جد",
        "culture": "مصر باستان",
        "energy": ["ثبات", "قدرت"],
        "uses": ["success", "general"],
        "description": "نماد ستون فقرات اوزیریس؛ نشانهٔ ثبات و قدرت.",
    },
    "was_scepter": {
        "name": "عصای واس",
        "culture": "مصر باستان",
        "energy": ["قدرت", "اقتدار"],
        "uses": ["success"],
        "description": "نماد اقتدار و قدرت الهی.",
    },
    "shen_ring": {
        "name": "حلقهٔ شن",
        "culture": "مصر باستان",
        "energy": ["حفاظت", "بی‌نهایت"],
        "uses": ["protection", "general"],
        "description": "نماد محافظت و بی‌نهایت.",
    },
    "feather_of_maat": {
        "name": "پرِ ماعت",
        "culture": "مصر باستان",
        "energy": ["عدالت", "تعادل"],
        "uses": ["spiritual", "general"],
        "description": "نماد عدالت، حقیقت و تعادل.",
    },
    "sphinx": {
        "name": "اسفنکس",
        "culture": "مصر باستان",
        "energy": ["حکمت", "محافظت"],
        "uses": ["protection", "spiritual"],
        "description": "نماد محافظت و خرد پنهان.",
    },
    "ankh_cross": {
        "name": "صلیب عنخ",
        "culture": "مصر باستان",
        "energy": ["زندگی", "نور"],
        "uses": ["spiritual"],
        "description": "نسخهٔ آیینی نماد عنخ؛ نماد زندگی و نور.",
    },
    "ka_symbol": {
        "name": "نماد کا",
        "culture": "مصر باستان",
        "energy": ["روح", "قدرت درونی"],
        "uses": ["spiritual"],
        "description": "نماد نیروی حیاتی و روح در مصر باستان.",
    },
    "ba_bird": {
        "name": "پرندهٔ با",
        "culture": "مصر باستان",
        "energy": ["آگاهی", "آزادی"],
        "uses": ["spiritual", "calm"],
        "description": "نماد روح آزاد و آگاهی.",
    },
    "udjat": {
        "name": "اوجات",
        "culture": "مصر باستان",
        "energy": ["محافظت", "سلامت"],
        "uses": ["protection"],
        "description": "نسخهٔ کامل چشم هوروس؛ نماد محافظت و سلامت.",
    },
    "ankh_key": {
        "name": "کلید زندگی",
        "culture": "مصر باستان",
        "energy": ["قدرت", "آگاهی"],
        "uses": ["spiritual", "success"],
        "description": "نماد کلید زندگی و آگاهی.",
    },
    "sun_disk": {
        "name": "دیسک خورشید",
        "culture": "مصر باستان",
        "energy": ["نور", "قدرت"],
        "uses": ["success", "general"],
        "description": "نماد خورشید و انرژی الهی.",
    },
    "ankh_lotus": {
        "name": "عنخ لوتوس",
        "culture": "مصر باستان",
        "energy": ["زندگی", "پاکی"],
        "uses": ["spiritual", "calm"],
        "description": "ترکیب عنخ و لوتوس؛ نماد زندگی و پاکی.",
    },
    "cobra_uraeus": {
        "name": "مار کبری اورائوس",
        "culture": "مصر باستان",
        "energy": ["محافظت", "اقتدار"],
        "uses": ["protection"],
        "description": "نماد سلطنتی محافظت و اقتدار.",
    },
    "ankh_scarab": {
        "name": "عنخ–سوسک",
        "culture": "مصر باستان",
        "energy": ["زندگی", "تولد دوباره"],
        "uses": ["spiritual", "success"],
        "description": "ترکیب دو نماد قدرتمند زندگی و تولد دوباره.",
    },
    "papyrus_symbol": {
        "name": "نماد پاپیروس",
        "culture": "مصر باستان",
        "energy": ["دانش", "رشد"],
        "uses": ["spiritual", "general"],
        "description": "نماد دانش، نوشتن و رشد.",
    },
}
