GLOBAL_ARCHETYPES = {
    "the_hero": {
        "name": "قهرمان",
        "culture": "جهانی",
        "energy": ["قدرت", "اراده", "شجاعت"],
        "uses": ["success", "protection"],
        "description": "آرکتایپ قهرمان نماد اراده، شجاعت و غلبه بر چالش‌هاست.",
    },
    "the_sage": {
        "name": "حکیم",
        "culture": "جهانی",
        "energy": ["حکمت", "آگاهی"],
        "uses": ["spiritual", "general"],
        "description": "نماد خرد، بینش و آگاهی عمیق.",
    },
    "the_lover": {
        "name": "عاشق",
        "culture": "جهانی",
        "energy": ["عشق", "جذب", "زیبایی"],
        "uses": ["love"],
        "description": "نماد عشق، جذابیت و پیوند احساسی.",
    },
    "the_creator": {
        "name": "آفریننده",
        "culture": "جهانی",
        "energy": ["خلاقیت", "نوآوری"],
        "uses": ["success", "general"],
        "description": "نماد خلاقیت، نوآوری و ساختن.",
    },
    "the_magician": {
        "name": "جادوگر",
        "culture": "جهانی",
        "energy": ["تغییر", "آگاهی"],
        "uses": ["spiritual", "success"],
        "description": "نماد دگرگونی، آگاهی و قدرت درونی.",
    },
    "the_caretaker": {
        "name": "حامی",
        "culture": "جهانی",
        "energy": ["حمایت", "مهربانی"],
        "uses": ["calm", "general"],
        "description": "نماد مراقبت، حمایت و مهربانی.",
    },
    "the_warrior": {
        "name": "جنگجو",
        "culture": "جهانی",
        "energy": ["قدرت", "تمرکز"],
        "uses": ["success", "protection"],
        "description": "نماد قدرت، تمرکز و ارادهٔ شکست‌ناپذیر.",
    },
    "the_king": {
        "name": "پادشاه",
        "culture": "جهانی",
        "energy": ["اقتدار", "ثبات"],
        "uses": ["success", "general"],
        "description": "نماد نظم، اقتدار و رهبری.",
    },
    "the_queen": {
        "name": "ملکه",
        "culture": "جهانی",
        "energy": ["زیبایی", "قدرت درونی"],
        "uses": ["love", "success"],
        "description": "نماد قدرت درونی، زیبایی و شکوه.",
    },
    "the_child": {
        "name": "کودک",
        "culture": "جهانی",
        "energy": ["معصومیت", "آغاز"],
        "uses": ["calm", "general"],
        "description": "نماد آغاز، پاکی و انرژی تازه.",
    },
    "the_shadow": {
        "name": "سایه",
        "culture": "جهانی",
        "energy": ["آگاهی", "رشد"],
        "uses": ["spiritual"],
        "description": "نماد بخش‌های پنهان روان که به رشد منجر می‌شوند.",
    },
    "the_healer": {
        "name": "شفادهنده",
        "culture": "جهانی",
        "energy": ["شفا", "آرامش"],
        "uses": ["calm", "spiritual"],
        "description": "نماد شفا، آرامش و انرژی مثبت.",
    },
    "the_trickster": {
        "name": "نقاب‌زن",
        "culture": "جهانی",
        "energy": ["هوش", "انعطاف"],
        "uses": ["success"],
        "description": "نماد هوش، بازیگوشی و تغییر مسیرهای غیرمنتظره.",
    },
    "the_explorer": {
        "name": "کاوشگر",
        "culture": "جهانی",
        "energy": ["آزادی", "جستجو"],
        "uses": ["general", "success"],
        "description": "نماد آزادی، ماجراجویی و کشف ناشناخته‌ها.",
    },
    "the_mother": {
        "name": "مادر",
        "culture": "جهانی",
        "energy": ["حمایت", "عشق"],
        "uses": ["love", "calm"],
        "description": "نماد عشق بی‌قید و شرط و حمایت.",
    },
    "the_father": {
        "name": "پدر",
        "culture": "جهانی",
        "energy": ["قدرت", "حمایت"],
        "uses": ["protection", "general"],
        "description": "نماد قدرت، مسئولیت و حمایت.",
    },
    "the_innocent": {
        "name": "معصوم",
        "culture": "جهانی",
        "energy": ["پاکی", "امید"],
        "uses": ["calm", "general"],
        "description": "نماد امید، پاکی و نیت خوب.",
    },
    "the_rebel": {
        "name": "یاغی",
        "culture": "جهانی",
        "energy": ["تغییر", "قدرت"],
        "uses": ["success"],
        "description": "نماد تغییر، جسارت و شکستن محدودیت‌ها.",
    },
    "the_wise_old_man": {
        "name": "پیر دانا",
        "culture": "جهانی",
        "energy": ["حکمت", "هدایت"],
        "uses": ["spiritual"],
        "description": "نماد خرد عمیق و هدایت معنوی.",
    },
    "the_mystic": {
        "name": "عارف",
        "culture": "جهانی",
        "energy": ["آگاهی", "تعالی"],
        "uses": ["spiritual"],
        "description": "نماد شهود، آگاهی و اتصال معنوی.",
    },
}
