GREEK_ROMAN_SYMBOLS = {
    "venus": {
        "name": "ونوس",
        "culture": "روم",
        "energy": ["عشق", "زیبایی", "هماهنگی"],
        "uses": ["love", "calm"],
        "description": "الههٔ عشق و زیبایی در روم؛ یکی از قدرتمندترین نمادهای عشق در جهان.",
    },
    "aphrodite": {
        "name": "آفرودیت",
        "culture": "یونان",
        "energy": ["عشق", "جذب", "زیبایی"],
        "uses": ["love"],
        "description": "الههٔ عشق و جذابیت در یونان باستان.",
    },
    "eros": {
        "name": "اروس",
        "culture": "یونان",
        "energy": ["عشق", "اشتیاق"],
        "uses": ["love"],
        "description": "ایزد عشق و اشتیاق؛ نماد جذب و پیوند احساسی.",
    },
    "psyche": {
        "name": "سایکی",
        "culture": "یونان",
        "energy": ["روح", "عشق پاک"],
        "uses": ["love", "spiritual"],
        "description": "نماد روح و عشق پاک در اسطوره‌های یونانی.",
    },
    "zeus": {
        "name": "زئوس",
        "culture": "یونان",
        "energy": ["قدرت", "اقتدار"],
        "uses": ["success"],
        "description": "پادشاه خدایان یونان؛ نماد قدرت و پیروزی.",
    },
    "jupiter_symbol": {
        "name": "نماد ژوپیتر",
        "culture": "روم",
        "energy": ["گسترش", "ثروت", "شانس"],
        "uses": ["wealth", "success", "general"],
        "description": "نماد مشتری؛ سیارهٔ گسترش، ثروت و خوش‌شانسی.",
    },
    "hermes": {
        "name": "هرمس",
        "culture": "یونان",
        "energy": ["ارتباط", "هوش", "سفر"],
        "uses": ["success", "general"],
        "description": "ایزد پیام‌رسان و نماد سرعت، هوش و ارتباط.",
    },
    "mercury_symbol": {
        "name": "نماد مرکوری",
        "culture": "روم",
        "energy": ["ارتباط", "تجارت"],
        "uses": ["success", "wealth"],
        "description": "نماد سیارهٔ عطارد؛ مرتبط با تجارت و ارتباط.",
    },
    "apollo": {
        "name": "آپولو",
        "culture": "یونان",
        "energy": ["نور", "هنر", "شفا"],
        "uses": ["calm", "spiritual"],
        "description": "ایزد نور، هنر و شفا در یونان.",
    },
    "artemis": {
        "name": "آرتمیس",
        "culture": "یونان",
        "energy": ["محافظت", "پاکی"],
        "uses": ["protection"],
        "description": "الههٔ شکار و محافظت؛ نماد پاکی و قدرت.",
    },
    "diana": {
        "name": "دیانا",
        "culture": "روم",
        "energy": ["محافظت", "ماه"],
        "uses": ["protection", "calm"],
        "description": "الههٔ ماه و محافظت در روم.",
    },
    "athena": {
        "name": "آتنا",
        "culture": "یونان",
        "energy": ["حکمت", "استراتژی"],
        "uses": ["success", "spiritual"],
        "description": "الههٔ خرد و استراتژی؛ نماد هوش و پیروزی.",
    },
    "minerva": {
        "name": "مینروا",
        "culture": "روم",
        "energy": ["حکمت", "هنر"],
        "uses": ["success"],
        "description": "الههٔ خرد و هنر در روم.",
    },
    "poseidon": {
        "name": "پوسایدون",
        "culture": "یونان",
        "energy": ["قدرت", "آب"],
        "uses": ["success", "calm"],
        "description": "ایزد دریا؛ نماد قدرت و جریان.",
    },
    "neptune": {
        "name": "نپتون",
        "culture": "روم",
        "energy": ["آب", "قدرت"],
        "uses": ["calm", "success"],
        "description": "همتای رومی پوسایدون.",
    },
    "hestia": {
        "name": "هستیا",
        "culture": "یونان",
        "energy": ["آرامش", "خانه"],
        "uses": ["calm"],
        "description": "الههٔ آتش خانگی و آرامش.",
    },
    "vesta": {
        "name": "وستا",
        "culture": "روم",
        "energy": ["آرامش", "پاکی"],
        "uses": ["calm", "spiritual"],
        "description": "الههٔ آتش مقدس در روم.",
    },
    "hades": {
        "name": "هادس",
        "culture": "یونان",
        "energy": ["قدرت درونی", "ثبات"],
        "uses": ["spiritual"],
        "description": "ایزد دنیای زیرین؛ نماد قدرت درونی و استقامت.",
    },
    "demeter": {
        "name": "دمتر",
        "culture": "یونان",
        "energy": ["باروری", "فراوانی"],
        "uses": ["wealth", "general"],
        "description": "الههٔ زمین و فراوانی.",
    },
    "persephone": {
        "name": "پرسفون",
        "culture": "یونان",
        "energy": ["تغییر", "رشد"],
        "uses": ["spiritual", "calm"],
        "description": "الههٔ بهار و دگرگونی.",
    },
}
