HINDU_SYMBOLS = {
    "om": {
        "name": "اوم (ॐ)",
        "culture": "هند",
        "energy": ["آگاهی", "آرامش", "تعالی"],
        "uses": ["calm", "spiritual"],
        "description": "مقدس‌ترین مانترا در هندوئیسم؛ نماد آگاهی و آرامش.",
    },
    "lakshmi": {
        "name": "لکشمی",
        "culture": "هند",
        "energy": ["ثروت", "فراوانی", "برکت"],
        "uses": ["wealth", "general"],
        "description": "الههٔ ثروت و فراوانی؛ یکی از قدرتمندترین نمادهای جذب برکت.",
    },
    "ganesha": {
        "name": "گانشا",
        "culture": "هند",
        "energy": ["رفع موانع", "موفقیت"],
        "uses": ["success", "general"],
        "description": "الههٔ رفع موانع؛ نماد شروع‌های موفق و پیروزی.",
    },
    "durga": {
        "name": "دورگا",
        "culture": "هند",
        "energy": ["قدرت", "محافظت"],
        "uses": ["protection", "success"],
        "description": "الههٔ قدرت و محافظت؛ نماد پیروزی بر منفی‌ها.",
    },
    "kali": {
        "name": "کالی",
        "culture": "هند",
        "energy": ["رهایی", "تغییر"],
        "uses": ["spiritual"],
        "description": "الههٔ دگرگونی و رهایی؛ نماد تغییر مثبت.",
    },
    "shiva": {
        "name": "شیوا",
        "culture": "هند",
        "energy": ["آگاهی", "قدرت درونی"],
        "uses": ["spiritual", "calm"],
        "description": "نماد آگاهی برتر و قدرت درونی.",
    },
    "trishula": {
        "name": "تریشولا",
        "culture": "هند",
        "energy": ["حفاظت", "قدرت"],
        "uses": ["protection"],
        "description": "نیزهٔ سه‌شاخهٔ شیوا؛ نماد محافظت و قدرت.",
    },
    "lotus": {
        "name": "لوتوس",
        "culture": "هند",
        "energy": ["پاکی", "رشد معنوی"],
        "uses": ["spiritual", "calm"],
        "description": "گل نیلوفر؛ نماد پاکی، رشد و بیداری.",
    },
    "yantra": {
        "name": "یانترای مقدس",
        "culture": "هند",
        "energy": ["تمرکز", "قدرت ذهن"],
        "uses": ["spiritual", "general"],
        "description": "نماد هندسی مقدس برای تمرکز و انرژی مثبت.",
    },
    "sri_yantra": {
        "name": "شری یانترا",
        "culture": "هند",
        "energy": ["ثروت", "قدرت معنوی"],
        "uses": ["wealth", "spiritual"],
        "description": "قدرتمندترین یانترا؛ نماد ثروت و انرژی کیهانی.",
    },
    "rudraksha": {
        "name": "رودراکشا",
        "culture": "هند",
        "energy": ["محافظت", "آرامش"],
        "uses": ["protection", "calm"],
        "description": "دانهٔ مقدس شیوا؛ نماد محافظت و آرامش ذهن.",
    },
    "chakra_symbol": {
        "name": "نماد چاکرا",
        "culture": "هند",
        "energy": ["تعادل", "آگاهی"],
        "uses": ["spiritual", "calm"],
        "description": "نماد سیستم انرژی بدن؛ برای تعادل و آگاهی.",
    },
    "third_eye": {
        "name": "چشم سوم",
        "culture": "هند",
        "energy": ["شهود", "آگاهی"],
        "uses": ["spiritual"],
        "description": "نماد شهود و دید درونی.",
    },
    "nandi": {
        "name": "ناندی",
        "culture": "هند",
        "energy": ["وفاداری", "قدرت"],
        "uses": ["success", "protection"],
        "description": "گاو مقدس شیوا؛ نماد قدرت و وفاداری.",
    },
    "hanuman": {
        "name": "هانومان",
        "culture": "هند",
        "energy": ["شجاعت", "قدرت"],
        "uses": ["success", "protection"],
        "description": "نماد شجاعت، وفاداری و قدرت معنوی.",
    },
    "peacock_feather": {
        "name": "پر طاووس",
        "culture": "هند",
        "energy": ["زیبایی", "محافظت"],
        "uses": ["protection", "general"],
        "description": "نماد زیبایی و محافظت در سنت هندی.",
    },
    "bindi": {
        "name": "بیندی",
        "culture": "هند",
        "energy": ["تمرکز", "آگاهی"],
        "uses": ["spiritual"],
        "description": "نقطهٔ مقدس پیشانی؛ نماد تمرکز و آگاهی.",
    },
    "rangoli": {
        "name": "رنگولی",
        "culture": "هند",
        "energy": ["برکت", "زیبایی"],
        "uses": ["wealth", "general"],
        "description": "نقش‌های رنگی آیینی؛ نماد برکت و انرژی مثبت.",
    },
    "swastika_positive": {
        "name": "سواستیکای مثبت هندی",
        "culture": "هند",
        "energy": ["برکت", "فراوانی"],
        "uses": ["wealth", "general"],
        "description": "نماد باستانی برکت و فراوانی در هند (کاملاً مثبت و بی‌خطر).",
    },
    "ganga": {
        "name": "گانگا",
        "culture": "هند",
        "energy": ["پاکی", "جریان"],
        "uses": ["calm", "spiritual"],
        "description": "الههٔ رود گنگ؛ نماد پاکی و جریان انرژی.",
    },
}
