MESOPOTAMIAN_SYMBOLS = {
    "dingir": {
        "name": "دینگیر (𒀭)",
        "culture": "سومر/بین‌النهرین",
        "energy": ["آسمان", "قدرت الهی"],
        "uses": ["spiritual", "general"],
        "description": "نماد ستاره‌ای دینگیر؛ نشانهٔ قدرت الهی و آسمانی.",
    },
    "lamassu": {
        "name": "لاماسو",
        "culture": "آشور",
        "energy": ["محافظت", "قدرت"],
        "uses": ["protection", "success"],
        "description": "موجود محافظ با سر انسان و بدن گاو یا شیر؛ نماد قدرت و حفاظت.",
    },
    "ishtar_star": {
        "name": "ستارهٔ ایشتار",
        "culture": "بابل",
        "energy": ["عشق", "قدرت", "جذب"],
        "uses": ["love", "success"],
        "description": "ستارهٔ هشت‌پر ایشتار؛ نماد عشق، قدرت و جذابیت.",
    },
    "ishtar_gate_rosette": {
        "name": "رزت دروازهٔ ایشتار",
        "culture": "بابل",
        "energy": ["زیبایی", "برکت"],
        "uses": ["general", "wealth"],
        "description": "نماد گل رزت روی دروازهٔ ایشتار؛ نشانهٔ زیبایی و برکت.",
    },
    "shamash_symbol": {
        "name": "نماد شاماش",
        "culture": "بابل",
        "energy": ["نور", "عدالت"],
        "uses": ["spiritual", "success"],
        "description": "ایزد خورشید و عدالت؛ نماد نور و حقیقت.",
    },
    "marduk_dragon": {
        "name": "اژدهای مردوک",
        "culture": "بابل",
        "energy": ["قدرت", "پیروزی"],
        "uses": ["success", "protection"],
        "description": "اژدهای مقدس مردوک؛ نماد قدرت و پیروزی.",
    },
    "nanna_moon": {
        "name": "ماه نانا",
        "culture": "سومر",
        "energy": ["آرامش", "آگاهی"],
        "uses": ["calm", "spiritual"],
        "description": "نماد ماه و آگاهی در سنت سومری.",
    },
    "enkidu_symbol": {
        "name": "نماد انکیدو",
        "culture": "سومر",
        "energy": ["قدرت طبیعی", "آزادی"],
        "uses": ["success", "general"],
        "description": "نماد قدرت طبیعی، آزادی و نیروی حیاتی.",
    },
    "gilgamesh_symbol": {
        "name": "نماد گیلگمش",
        "culture": "سومر/بابل",
        "energy": ["قدرت", "اراده"],
        "uses": ["success"],
        "description": "قهرمان اسطوره‌ای؛ نماد قدرت، اراده و جستجوی حقیقت.",
    },
    "udug_protection": {
        "name": "نماد محافظتی اودوگ",
        "culture": "بین‌النهرین",
        "energy": ["محافظت", "دفع منفی"],
        "uses": ["protection"],
        "description": "نماد باستانی محافظت در برابر انرژی‌های منفی.",
    },
    "cuneiform_star": {
        "name": "ستارهٔ میخی",
        "culture": "سومر",
        "energy": ["نور", "دانش"],
        "uses": ["spiritual", "general"],
        "description": "ستارهٔ میخی سومری؛ نماد نور و دانش.",
    },
    "ishtar_lion": {
        "name": "شیر ایشتار",
        "culture": "بابل",
        "energy": ["قدرت", "شجاعت"],
        "uses": ["success", "protection"],
        "description": "شیر مقدس ایشتار؛ نماد قدرت و شجاعت.",
    },
    "nammu_water": {
        "name": "نماد نامّو",
        "culture": "سومر",
        "energy": ["آب", "آفرینش"],
        "uses": ["spiritual", "calm"],
        "description": "الههٔ آب و آفرینش؛ نماد جریان و زندگی.",
    },
    "ishtar_bow": {
        "name": "کمان ایشتار",
        "culture": "بابل",
        "energy": ["قدرت", "تمرکز"],
        "uses": ["success"],
        "description": "نماد تمرکز، قدرت و هدف‌گیری دقیق.",
    },
    "tablet_of_destiny": {
        "name": "لوح سرنوشت",
        "culture": "بین‌النهرین",
        "energy": ["قدرت", "حکمت"],
        "uses": ["spiritual", "general"],
        "description": "نماد حکمت و قدرت تعیین مسیر زندگی.",
    },
    "winged_sun": {
        "name": "خورشید بالدار",
        "culture": "آشور/بابل",
        "energy": ["نور", "محافظت"],
        "uses": ["protection", "success"],
        "description": "نماد خورشید بالدار؛ نشانهٔ نور و محافظت.",
    },
    "ishtar_rose": {
        "name": "گل ایشتار",
        "culture": "بابل",
        "energy": ["عشق", "زیبایی"],
        "uses": ["love", "general"],
        "description": "نماد زیبایی و عشق در سنت ایشتار.",
    },
    "bull_of_heaven": {
        "name": "گاو آسمانی",
        "culture": "سومر",
        "energy": ["قدرت", "فراوانی"],
        "uses": ["wealth", "success"],
        "description": "نماد قدرت آسمانی و فراوانی.",
    },
    "ishtar_circle": {
        "name": "دایرهٔ ایشتار",
        "culture": "بابل",
        "energy": ["تعادل", "هماهنگی"],
        "uses": ["calm", "general"],
        "description": "دایرهٔ مقدس ایشتار؛ نماد تعادل و هماهنگی.",
    },
    "sumerian_tree": {
        "name": "درخت سومری",
        "culture": "سومر",
        "energy": ["رشد", "حکمت"],
        "uses": ["spiritual", "general"],
        "description": "نماد درخت زندگی سومری؛ نشانهٔ رشد و حکمت.",
    },
}
