SHAMANIC_SYMBOLS = {
    "medicine_wheel": {
        "name": "چرخ پزشکی",
        "culture": "شمنی/بومی آمریکا",
        "energy": ["تعادل", "شفا"],
        "uses": ["spiritual", "calm"],
        "description": "نماد تعادل چهار جهت و چهار عنصر؛ برای شفا و هماهنگی.",
    },
    "dreamcatcher": {
        "name": "دریم‌کچر",
        "culture": "شمنی",
        "energy": ["محافظت", "آرامش"],
        "uses": ["protection", "calm"],
        "description": "نماد محافظت از خواب و دفع انرژی‌های منفی.",
    },
    "shaman_drum": {
        "name": "طبل شمنی",
        "culture": "شمنی",
        "energy": ["قدرت", "جریان انرژی"],
        "uses": ["spiritual", "general"],
        "description": "طبل آیینی برای اتصال با انرژی طبیعت.",
    },
    "feather_symbol": {
        "name": "پر مقدس",
        "culture": "شمنی",
        "energy": ["آگاهی", "آزادی"],
        "uses": ["spiritual", "calm"],
        "description": "پر نماد آگاهی، آزادی و ارتباط با آسمان است.",
    },
    "animal_spirit_bear": {
        "name": "روح حیوانی — خرس",
        "culture": "شمنی",
        "energy": ["قدرت", "حفاظت"],
        "uses": ["protection", "success"],
        "description": "خرس نماد قدرت، شجاعت و محافظت است.",
    },
    "animal_spirit_wolf": {
        "name": "روح حیوانی — گرگ",
        "culture": "شمنی",
        "energy": ["شهود", "وفاداری"],
        "uses": ["spiritual", "protection"],
        "description": "گرگ نماد شهود، خرد و محافظت است.",
    },
    "animal_spirit_eagle": {
        "name": "روح حیوانی — عقاب",
        "culture": "شمنی",
        "energy": ["بینش", "قدرت"],
        "uses": ["success", "spiritual"],
        "description": "عقاب نماد بینش، قدرت و آگاهی بالاست.",
    },
    "animal_spirit_owl": {
        "name": "روح حیوانی — جغد",
        "culture": "شمنی",
        "energy": ["حکمت", "بینش پنهان"],
        "uses": ["spiritual"],
        "description": "جغد نماد خرد پنهان و شهود است.",
    },
    "animal_spirit_horse": {
        "name": "روح حیوانی — اسب",
        "culture": "شمنی",
        "energy": ["آزادی", "قدرت"],
        "uses": ["success", "general"],
        "description": "اسب نماد آزادی، حرکت و قدرت حیاتی است.",
    },
    "animal_spirit_fox": {
        "name": "روح حیوانی — روباه",
        "culture": "شمنی",
        "energy": ["هوش", "چابکی"],
        "uses": ["success"],
        "description": "روباه نماد هوش، چابکی و سازگاری است.",
    },
    "shamanic_eye": {
        "name": "چشم شمنی",
        "culture": "شمنی",
        "energy": ["شهود", "محافظت"],
        "uses": ["protection", "spiritual"],
        "description": "نماد دید درونی و محافظت معنوی.",
    },
    "four_directions": {
        "name": "چهار جهت مقدس",
        "culture": "شمنی",
        "energy": ["تعادل", "هماهنگی"],
        "uses": ["general", "calm"],
        "description": "نماد چهار جهت و چهار انرژی اصلی طبیعت.",
    },
    "shamanic_spiral": {
        "name": "مارپیچ شمنی",
        "culture": "شمنی",
        "energy": ["رشد", "چرخهٔ زندگی"],
        "uses": ["spiritual", "calm"],
        "description": "نماد چرخهٔ زندگی، رشد و حرکت انرژی.",
    },
    "shamanic_mask": {
        "name": "نقاب شمنی",
        "culture": "شمنی",
        "energy": ["قدرت درونی", "آگاهی"],
        "uses": ["spiritual"],
        "description": "نماد آگاهی درونی و قدرت روح.",
    },
    "totem_pole": {
        "name": "توتم",
        "culture": "شمنی/بومی آمریکا",
        "energy": ["هویت", "محافظت"],
        "uses": ["protection", "general"],
        "description": "نماد هویت قبیله‌ای و محافظت معنوی.",
    },
    "shamanic_fire": {
        "name": "آتش شمنی",
        "culture": "شمنی",
        "energy": ["پاک‌سازی", "قدرت"],
        "uses": ["spiritual", "success"],
        "description": "نماد آتش مقدس برای پاک‌سازی و قدرت.",
    },
    "shamanic_water": {
        "name": "آب مقدس",
        "culture": "شمنی",
        "energy": ["جریان", "آرامش"],
        "uses": ["calm", "spiritual"],
        "description": "نماد جریان انرژی و پاکی.",
    },
    "shamanic_moon": {
        "name": "ماه شمنی",
        "culture": "شمنی",
        "energy": ["شهود", "آرامش"],
        "uses": ["calm", "spiritual"],
        "description": "نماد ماه و انرژی شهودی.",
    },
    "shamanic_sun": {
        "name": "خورشید شمنی",
        "culture": "شمنی",
        "energy": ["قدرت", "نور"],
        "uses": ["success", "general"],
        "description": "نماد خورشید و انرژی حیاتی.",
    },
    "shamanic_wind": {
        "name": "باد مقدس",
        "culture": "شمنی",
        "energy": ["تغییر", "جریان"],
        "uses": ["general", "calm"],
        "description": "نماد تغییر، حرکت و جریان انرژی.",
    },
}
